# Generated by Django 5.0.1 on 2024-03-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barterrequest',
            name='address',
            field=models.CharField(default='Unknown Address', max_length=255),
        ),
        migrations.AddField(
            model_name='barterrequest',
            name='phone_number',
            field=models.CharField(default=9325462397, max_length=15),
        ),
    ]
