# Generated by Django 5.0.1 on 2024-03-07 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_barterrequest_address_barterrequest_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='seller',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
